=== Azure/AzPolicyLens/security-controls/security-control.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/taoyangcloud/azpolicylens/schemas/2025-09-01/security-control.json",
  "title": "Custom Security Control Config Schema",
  "type": "object",
  "properties": {
    "ControlID": {
      "type": "string",
      "pattern": "^\\S+$"
    },
    "Category": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "Publisher": {
      "type": "string"
    },
    "Framework": {
      "type": "string"
    },
    "AdditionalInfo": {
      "type": "object"
    }
  },
  "required": [
    "ControlID",
    "Category",
    "Name",
    "Description",
    "Publisher",
    "Framework",
    "AdditionalInfo"
  ]
}

=== Azure/AzPolicyLens/security-controls/contoso-bank-azure-control/CB-AZ-008.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "CB-AZ-008",
  "Category": "Networking",
  "Name": "Virtual Network Segmentation",
  "Description": "Separate production, development, and test workloads into isolated VNets.",
  "Publisher": "Contoso Bank",
  "Framework": "Contoso Bank Azure Security Control Framework",
  "AdditionalInfo": {
    "Action": "Apply NSGs and route tables to control inter-VNet traffic.",
    "LastUpdatedDate": "September 2025",
    "Link": "https://contosowebsite.azurewebsites.net/",
    "Version": "1.0.0",
    "Note": "This dummy control is generated by ChatGPT. It is designed for demonstration purposes only."
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.7.8.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.7.8",
  "Category": "Physical Controls",
  "Name": "Equipment siting and protection",
  "Description": "Equipment shall be sited securely and protected.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.5.31.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.5.31",
  "Category": "Organizational Controls",
  "Name": "Legal, statutory, regulatory and contractual requirements",
  "Description": "Legal, statutory, regulatory and contractual requirements relevant to information security and the organization's approach to meet these requirements shall be identified, documented and kept up to date.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.5.36.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.5.36",
  "Category": "Organizational Controls",
  "Name": "Compliance with policies, rules and standards for information security",
  "Description": "Compliance with the organization's information security policy, topic-specific policies, rules and standards shall be regularly reviewed.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.8.31.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.8.31",
  "Category": "Technological Controls",
  "Name": "Separation of development, test and production environments",
  "Description": "Development, testing and production environments shall be separated and secured.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/contoso-bank-azure-control/CB-AZ-048.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "CB-AZ-048",
  "Category": "Endpoint Security",
  "Name": "Device Compliance",
  "Description": "Enforce device compliance before accessing Azure resources.",
  "Publisher": "Contoso Bank",
  "Framework": "Contoso Bank Azure Security Control Framework",
  "AdditionalInfo": {
    "Action": "Integrate Intune with Conditional Access policies.",
    "LastUpdatedDate": "September 2025",
    "Link": "https://contosowebsite.azurewebsites.net/",
    "Version": "1.0.0",
    "Note": "This dummy control is generated by ChatGPT. It is designed for demonstration purposes only."
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.7.7.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.7.7",
  "Category": "Physical Controls",
  "Name": "Clear desk and clear screen",
  "Description": "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.5.24.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.5.24",
  "Category": "Organizational Controls",
  "Name": "Information security incident management planning and preparation",
  "Description": "The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}
