=== Azure/AzPolicyLens/security-controls/security-control.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/taoyangcloud/azpolicylens/schemas/2025-09-01/security-control.json",
  "title": "Custom Security Control Config Schema",
  "type": "object",
  "properties": {
    "ControlID": {
      "type": "string",
      "pattern": "^\\S+$"
    },
    "Category": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "Publisher": {
      "type": "string"
    },
    "Framework": {
      "type": "string"
    },
    "AdditionalInfo": {
      "type": "object"
    }
  },
  "required": [
    "ControlID",
    "Category",
    "Name",
    "Description",
    "Publisher",
    "Framework",
    "AdditionalInfo"
  ]
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.5.6.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.5.6",
  "Category": "Organizational Controls",
  "Name": "Contact with special interest groups",
  "Description": "The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.8.5.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.8.5",
  "Category": "Technological Controls",
  "Name": "Secure authentication",
  "Description": "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.7.13.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.7.13",
  "Category": "Physical Controls",
  "Name": "Equipment maintenance",
  "Description": "Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.6.5.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.6.5",
  "Category": "People Controls",
  "Name": "Responsibilities after termination or change of employment",
  "Description": "Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.7.5.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.7.5",
  "Category": "Physical Controls",
  "Name": "Protecting against physical and environmental threats",
  "Description": "Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/iso27001-2022/iso27001-2022_a.8.30.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "ISO27001-2022_A.8.30",
  "Category": "Technological Controls",
  "Name": "Outsourced development",
  "Description": "The organization shall direct, monitor and review the activities related to outsourced system development.",
  "Publisher": "ISO/IEC",
  "Framework": "ISO 27001:2022",
  "AdditionalInfo": {
    "Edition": "3",
    "PublishDate": "2022-10"
  }
}

=== Azure/AzPolicyLens/security-controls/contoso-bank-azure-control/CB-AZ-019.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "CB-AZ-019",
  "Category": "Data Protection",
  "Name": "Data Masking",
  "Description": "Apply dynamic data masking on sensitive fields in databases.",
  "Publisher": "Contoso Bank",
  "Framework": "Contoso Bank Azure Security Control Framework",
  "AdditionalInfo": {
    "Action": "Protect PII in non-production environments.",
    "LastUpdatedDate": "September 2025",
    "Link": "https://contosowebsite.azurewebsites.net/",
    "Version": "1.0.0",
    "Note": "This dummy control is generated by ChatGPT. It is designed for demonstration purposes only."
  }
}

=== Azure/AzPolicyLens/security-controls/contoso-bank-azure-control/CB-AZ-035.json
{
  "$schema": "../security-control.schema.json",
  "ControlID": "CB-AZ-035",
  "Category": "Compliance & Governance",
  "Name": "Regulatory Compliance",
  "Description": "Continuously assess Azure resources against compliance standards.",
  "Publisher": "Contoso Bank",
  "Framework": "Contoso Bank Azure Security Control Framework",
  "AdditionalInfo": {
    "Action": "Use Microsoft Defender for Cloud regulatory dashboard.",
    "LastUpdatedDate": "September 2025",
    "Link": "https://contosowebsite.azurewebsites.net/",
    "Version": "1.0.0",
    "Note": "This dummy control is generated by ChatGPT. It is designed for demonstration purposes only."
  }
}
